export const FETCH_CARS = "FETCH_CARS";
export const RECEIVED_CARS_SUCCESS = 'RECEIVED_CARS_SUCCESS';
export const RECEIVED_CARS_ERROR = 'RECEIVED_CARS_ERROR';

export const FETCH_RANDOM_CAR = "FETCH_RANDOM_CAR";
export const RECEIVED_RANDOM_CAR_SUCCESS = "RECEIVED_RANDOM_CAR_SUCCESS";
export const RECEIVED_RANDOM_CAR_ERROR = "FETCH_RANDOM_CAR_ERROR";