export const FETCH_GET_CAR_VOTES = "FETCH_GET_CAR_VOTES";
export const RECEIVED_CAR_VOTES_SUCCESS = 'RECEIVED_CAR_VOTES_SUCCESS';
export const RECEIVED_CAR_VOTES_ERROR = 'RECEIVED_CAR_VOTES_ERROR';

export const FETCH_CAR_VOTE = "FETCH_CAR_VOTE";
export const VOTE_CAR_SUCCESS = "VOTE_CAR_SUCCESS";
export const VOTE_CAR_ERROR = "VOTE_CAR_ERROR";